version: "3.9"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend/
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    links:
      - backend

  backend:
    container_name: backend
    restart: always
    build:
      context: backend/
    expose:
      - 8000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    restart: always
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
